version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:latest
    container_name: postgres_for_wso2
    environment:
      - POSTGRES_USER=regadmin
      - POSTGRES_PASSWORD=regadmin
      - POSTGRES_DB=regadmin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wso2_network # Use a common network name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regadmin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Database Initialization Service
  db-init:
    image: postgres:latest
    container_name: db_init_for_wso2
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wso2_network # Use a common network name
    volumes:
      - ./dbscripts:/dbscripts
    environment:
      - PGPASSWORD=regadmin
    command: >
      bash -c "
        echo '---------Creating databases---------' &&
        psql -h db -U regadmin -c 'CREATE DATABASE \"WSO2_IDENTITY_DB\";' &&
        psql -h db -U regadmin -c 'CREATE DATABASE \"WSO2_SHARED_DB\";' &&
        echo '---------Executing scripts for WSO2_IDENTITY_DB---------' &&
        psql -h db -U regadmin -d WSO2_IDENTITY_DB -f /dbscripts/identity/postgresql.sql &&
        psql -h db -U regadmin -d WSO2_IDENTITY_DB -f /dbscripts/consent/postgresql.sql &&
        echo '---------Executing scripts for WSO2_SHARED_DB---------' &&
        psql -h db -U regadmin -d WSO2_SHARED_DB -f /dbscripts/postgresql.sql &&
        echo '---------Database initialization complete---------'
      "
      
  # WSO2 Identity Server Service
  identity-server:
    build: ../../dockerfiles/alpine/is/
    container_name: wso2_is
    ports:
      - "9443:9443"
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/console"]
      interval: 30s
      timeout: 20s
      start_period: 240s
      retries: 5
    depends_on:
      db-init: # It should wait for the db-init to complete
        condition: service_completed_successfully
    volumes:
      - ./conf/identity-server:/home/wso2carbon/wso2-config-volume
    networks:
      - wso2_network # Use a common network name

volumes:
  postgres_data:
    driver: local

networks:
  wso2_network: # Define the common network
    driver: bridge